version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "gradle"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    ignore:
      - dependency-name: "org.junit.jupiter:junit-jupiter"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.junit.vintage:junit-vintage-engine"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
