name: Pre-merge checks

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '.npmignore'
      - '.husky/**'
      - '.idea/**'
      - 'LICENSE'
      - 'NOTICE'
      - '*.md'
      - 'bumpver.toml'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.npmignore'
      - '.husky/**'
      - '.idea/**'
      - 'LICENSE'
      - 'NOTICE'
      - '*.md'
      - 'bumpver.toml'
      - 'package.json'
      - 'pnpm-lock.yaml'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 30
    name: Build and test (OS ${{ matrix.os }}, JDK ${{ matrix.jvm-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        jvm-version: [21]
        os: [ubuntu-latest]
    env:
      JDK_VERSION: ${{ matrix.jvm-version }}
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Ensure all code files have license headers
        if: matrix.os == 'ubuntu-latest' && matrix.jvm-version == '21'
        shell: bash
        run: ./script/ensure_license_headers.sh

      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: ${{ matrix.jvm-version }}
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1
        with:
          dependency-graph: generate-and-submit
          dependency-graph-continue-on-failure: false

      - name: Build and test
        shell: bash
        run: ./gradlew check koverLog --parallel --no-daemon -x iosX64Test

      - name: Boot simulator
        if: matrix.os == 'macos-14'
        shell: bash
        run: |
          xcrun simctl list
          xcrun simctl boot 'iPhone 16 Pro Max' || true

      - name: Run simulator tests
        if: matrix.os == 'macos-14'
        shell: bash
        run: ./gradlew -PiosDevice="iPhone 16 Pro Max" iosTest
