name: Pre-merge checks

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '.npmignore'
      - '.husky/**'
      - '.idea/**'
      - 'LICENSE'
      - 'NOTICE'
      - '*.md'
      - 'bumpver.toml'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.npmignore'
      - '.husky/**'
      - '.idea/**'
      - 'LICENSE'
      - 'NOTICE'
      - '*.md'
      - 'bumpver.toml'
      - 'package.json'
      - 'pnpm-lock.yaml'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test (OS ${{ matrix.os }}, JDK ${{ matrix.jvm-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        jvm-version: [21]
        os: [ubuntu-latest, macos-14]
    env:
      JDK_VERSION: ${{ matrix.jvm-version }}
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2 # set to a value > 1 to support codecov.io SHA detection

      - name: Ensure all code files have license headers
        if: matrix.os == 'ubuntu-latest' && matrix.jvm-version == '21'
        shell: bash
        run: ./script/ensure_license_headers.sh

      - name: Set up JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: ${{ matrix.jvm-version }}
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
        with:
          dependency-graph: generate-and-submit
          dependency-graph-continue-on-failure: false

      - name: Build and test
        shell: bash
        run: ./gradlew check koverLog --parallel --no-daemon -x iosX64Test

      - name: Boot simulator
        if: matrix.os == 'macos-14'
        shell: bash
        run: |
          xcrun simctl list
          xcrun simctl boot 'iPhone 16 Pro Max' || true

      - name: Run simulator tests
        if: matrix.os == 'macos-14'
        shell: bash
        run: ./gradlew -PiosDevice="iPhone 16 Pro Max" iosTest

      - name: Upload coverage stats
        if: success() && matrix.os == 'ubuntu-latest' && matrix.jvm-version == '21'
        uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3 # v5.3.1
