name: Pre-merge checks

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '.npmignore'
      - '.husky/**'
      - '.idea/**'
      - 'LICENSE'
      - 'NOTICE'
      - '*.md'
      - 'bumpver.toml'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.npmignore'
      - '.husky/**'
      - '.idea/**'
      - 'LICENSE'
      - 'NOTICE'
      - '*.md'
      - 'bumpver.toml'
      - 'package.json'
      - 'pnpm-lock.yaml'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 30
    name: Build and test (OS ${{ matrix.os }}, JDK ${{ matrix.jvm-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        jvm-version: [21]
        os: [ubuntu-latest]
    env:
      JDK_VERSION: ${{ matrix.jvm-version }}
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Ensure all code files have license headers
        if: matrix.os == 'ubuntu-latest' && matrix.jvm-version == '21'
        shell: bash
        run: ./script/ensure_license_headers.sh

      - name: Set up JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: ${{ matrix.jvm-version }}
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          dependency-graph: generate-and-submit
          dependency-graph-continue-on-failure: false

      - name: Build and test
        shell: bash
        run: ./gradlew check koverLog --parallel --no-daemon -x iosX64Test

      - name: Boot simulator
        if: matrix.os == 'macos-14'
        shell: bash
        run: |
          xcrun simctl list
          xcrun simctl boot 'iPhone 16 Pro Max' || true

      - name: Run simulator tests
        if: matrix.os == 'macos-14'
        shell: bash
        run: ./gradlew -PiosDevice="iPhone 16 Pro Max" iosTest
